
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";


import { UserGuard } from "app";



const App = lazy(() => import("./pages/App.tsx"));
const AssistantPage = lazy(() => import("./pages/AssistantPage.tsx"));
const CalendarPage = lazy(() => import("./pages/CalendarPage.tsx"));
const CalendarSettingsPage = lazy(() => import("./pages/CalendarSettingsPage.tsx"));
const ClientsPage = lazy(() => import("./pages/ClientsPage.tsx"));
const ContactPage = lazy(() => import("./pages/ContactPage.tsx"));
const CookiePolicyPage = lazy(() => import("./pages/CookiePolicyPage.tsx"));
const DashboardPage = lazy(() => import("./pages/DashboardPage.tsx"));
const InvoiceItemsPage = lazy(() => import("./pages/InvoiceItemsPage.tsx"));
const InvoicesPage = lazy(() => import("./pages/InvoicesPage.tsx"));
const LandingPage = lazy(() => import("./pages/LandingPage.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const Logout = lazy(() => import("./pages/Logout.tsx"));
const NotFoundPage = lazy(() => import("./pages/NotFoundPage.tsx"));
const PricingPage = lazy(() => import("./pages/PricingPage.tsx"));
const PrivacyPage = lazy(() => import("./pages/PrivacyPage.tsx"));
const SettingsPage = lazy(() => import("./pages/SettingsPage.tsx"));
const SharedInvoicePage = lazy(() => import("./pages/SharedInvoicePage.tsx"));
const StorageTestPage = lazy(() => import("./pages/StorageTestPage.tsx"));
const TermsPage = lazy(() => import("./pages/TermsPage.tsx"));
const TimeTrackingPage = lazy(() => import("./pages/TimeTrackingPage.tsx"));

export const userRoutes: RouteObject[] = [



	{ path: "/", element: <App />},
	{ path: "/assistant-page", element: <UserGuard><AssistantPage /></UserGuard>},
	{ path: "/assistantpage", element: <UserGuard><AssistantPage /></UserGuard>},
	{ path: "/calendar-page", element: <UserGuard><CalendarPage /></UserGuard>},
	{ path: "/calendarpage", element: <UserGuard><CalendarPage /></UserGuard>},
	{ path: "/calendar-settings-page", element: <UserGuard><CalendarSettingsPage /></UserGuard>},
	{ path: "/calendarsettingspage", element: <UserGuard><CalendarSettingsPage /></UserGuard>},
	{ path: "/clients-page", element: <UserGuard><ClientsPage /></UserGuard>},
	{ path: "/clientspage", element: <UserGuard><ClientsPage /></UserGuard>},
	{ path: "/contact-page", element: <ContactPage />},
	{ path: "/contactpage", element: <ContactPage />},
	{ path: "/cookie-policy-page", element: <CookiePolicyPage />},
	{ path: "/cookiepolicypage", element: <CookiePolicyPage />},
	{ path: "/dashboard-page", element: <UserGuard><DashboardPage /></UserGuard>},
	{ path: "/dashboardpage", element: <UserGuard><DashboardPage /></UserGuard>},
	{ path: "/invoice-items-page", element: <UserGuard><InvoiceItemsPage /></UserGuard>},
	{ path: "/invoiceitemspage", element: <UserGuard><InvoiceItemsPage /></UserGuard>},
	{ path: "/invoices-page", element: <UserGuard><InvoicesPage /></UserGuard>},
	{ path: "/invoicespage", element: <UserGuard><InvoicesPage /></UserGuard>},
	{ path: "/landing-page", element: <LandingPage />},
	{ path: "/landingpage", element: <LandingPage />},
	{ path: "/login", element: <Login />},
	{ path: "/logout", element: <Logout />},
	{ path: "/not-found-page", element: <NotFoundPage />},
	{ path: "/notfoundpage", element: <NotFoundPage />},
	{ path: "/pricing-page", element: <PricingPage />},
	{ path: "/pricingpage", element: <PricingPage />},
	{ path: "/privacy-page", element: <PrivacyPage />},
	{ path: "/privacypage", element: <PrivacyPage />},
	{ path: "/settings-page", element: <UserGuard><SettingsPage /></UserGuard>},
	{ path: "/settingspage", element: <UserGuard><SettingsPage /></UserGuard>},
	{ path: "/shared-invoice", element: <SharedInvoicePage />},
	{ path: "/shared-invoice-page", element: <SharedInvoicePage />},
	{ path: "/sharedinvoicepage", element: <SharedInvoicePage />},
	{ path: "/storage-test-page", element: <UserGuard><StorageTestPage /></UserGuard>},
	{ path: "/storagetestpage", element: <UserGuard><StorageTestPage /></UserGuard>},
	{ path: "/terms-page", element: <UserGuard><TermsPage /></UserGuard>},
	{ path: "/termspage", element: <UserGuard><TermsPage /></UserGuard>},
	{ path: "/time-tracking-page", element: <TimeTrackingPage />},
	{ path: "/timetrackingpage", element: <TimeTrackingPage />},

];
